// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc_2jGQO6IqEwch_Oog4Szlq6NnGzz7CY',
    appId: '1:155918649632:web:b63b3b57cb7b081c2f6f45',
    messagingSenderId: '155918649632',
    projectId: 'sos-alert-b187f',
    authDomain: 'sos-alert-b187f.firebaseapp.com',
    storageBucket: 'sos-alert-b187f.firebasestorage.app',
    measurementId: 'G-S5G9GKG5DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo83iMTPlAVc0DhdEpijf5FiHSXG4fUi0',
    appId: '1:155918649632:android:ca0aa8c502bce3082f6f45',
    messagingSenderId: '155918649632',
    projectId: 'sos-alert-b187f',
    storageBucket: 'sos-alert-b187f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc_2jGQO6IqEwch_Oog4Szlq6NnGzz7CY',
    appId: '1:155918649632:web:206bd8e38c3ebb1e2f6f45',
    messagingSenderId: '155918649632',
    projectId: 'sos-alert-b187f',
    authDomain: 'sos-alert-b187f.firebaseapp.com',
    storageBucket: 'sos-alert-b187f.firebasestorage.app',
    measurementId: 'G-4DC3HT7GV4',
  );
}
